# Generated by Django 5.2.3 on 2025-06-24 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdoInternacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_firma', models.DateField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Acuerdo Internacional',
                'verbose_name_plural': 'Acuerdos Internacionales',
                'db_table': 'acuerdo_internacional',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('poblacion', models.PositiveIntegerField()),
                ('pib', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'pais',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SectorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sector', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Sector Económico',
                'verbose_name_plural': 'Sectores Económicos',
                'db_table': 'sector_economico',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umbral', models.DecimalField(decimal_places=3, max_digits=12)),
                ('valor_emision', models.DecimalField(decimal_places=3, max_digits=12)),
                ('fecha_alerta', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
            options={
                'verbose_name': 'Alerta de Emisión',
                'verbose_name_plural': 'Alertas de Emisión',
                'db_table': 'alerta_emision',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaClimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion_politica', models.TextField()),
                ('fecha_publicacion', models.DateField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
            options={
                'verbose_name': 'Política Climática',
                'verbose_name_plural': 'Políticas Climáticas',
                'db_table': 'politica_climatica',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Emision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_co2e', models.DecimalField(decimal_places=3, max_digits=12)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sectoreconomico')),
            ],
            options={
                'verbose_name': 'Emisión',
                'verbose_name_plural': 'Emisiones',
                'db_table': 'emision',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaisAcuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adhesion', models.DateField()),
                ('acuerdo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acuerdointernacional')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
            options={
                'verbose_name': 'Adhesión de País a Acuerdo',
                'verbose_name_plural': 'Adhesiones de Países a Acuerdos',
                'db_table': 'pais_acuerdo',
                'ordering': ['id'],
                'unique_together': {('pais', 'acuerdo')},
            },
        ),
    ]
